import type { Metadata } from "next";
import { Open_Sans } from 'next/font/google';
import "./style.css";
import "@/app/globals.css";


const openSans = Open_Sans({
  subsets: ['latin'],  // Ensure proper character support
  weight: ['300', '400', '500', '600', '700'], // Specify font weights you need
});

export const metadata: Metadata = {
  title: "Compare the Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
